### ISSUE TITLE
Editor Crash when Selecting Nested Resource Values for Rewind

### ISSUE THREAD

**Issue by mendieta** [ImTani/godot-time-rewind-2d#3]
Hey there, the plugin is amazing, thanks! There's an issue when selecting nested value, for example I have a Resource for the attributes of the characters, it holds health, mana, stamina, etc. The Resource itself hold more Resources, I select `Attributes->Health->current_value` and the editor crashes, I am unsure if an error is thrown since the editor crashes as soon as i click on confirm on the properties panel. Also, how did you configure the settings to rewind the animations for the attack and jump on your demo?

Thank you again!!

**Comment by ImTani** [comment]
thanks for pointing this out! let me try recreating this issue, though the version of the plugin have is quite different. I will test this and fix it if its still broken. The update's gonna take a while though, I chewed off a bit too much this time around,

**Comment by ImTani** [comment]
@mendieta I believe the problem was coming around due to circular reference perhaps? I have fixed that pesky problem in a newer version of the plugin which should be live in a few hours (the issue made me power through it haha), test it then!

**Comment by mendieta** [comment]
@ImTani , thanks or the fast reply. Sorry I could not test the new version before, had a busy week.  Thank you fro pointing out how to record the animations!

Sadly the new version still has the same bug, or appears so,
![CleanShot 2024-10-26 at 11 55 20@2x](https://github.com/user-attachments/assets/9d5bb848-2206-4f00-b81b-e6005b50c76e)

When confirming the properties in the above image, it does not crash

![CleanShot 2024-10-26 at 11 56 09@2x](https://github.com/user-attachments/assets/7475725f-6b46-4ac1-b8a2-4ff71e3375ab)

When confirming enabling a value from the nested resource, it crashes. 


Let me know how i can help.

Thanks again

**Comment by ImTani** [comment]
Thanks for getting back to me! The release isn't available on the asset library yet, but I've just released it on the repository. You can download it from there if you don't want to wait!

**Comment by ImTani** [comment]
@mendieta The new update is on the asset store, kindly try it out.

**Comment by mendieta** [comment]
@ImTani thanks! I can confirm its working perfectly now! Thank you so much

**Comment by ImTani** [comment]
Awesome! Thanks for bringing the bug up! Enjoy the plugin!

**Comment by ImTani** [comment]
Issue resolved in Release [v1.0.1](https://github.com/ImTani/godot-time-rewind-2d/releases/tag/v1.0.1)
Closing the issue now.
